sudo: false
language: objective-c
xcode_project: PureLayout/PureLayout.xcodeproj
matrix:
  include:
    - xcode_sdk: iphonesimulator
      xcode_scheme: Example-iOS
    - xcode_sdk: macosx
      xcode_scheme: Example-Mac
